[project]
name = "si-prd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jerymy-k", email = "karimimoha0@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "imbalanced-learn>=0.14.2",
    "joblib>=1.6.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
si-prd = "si_prd:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
