FROM python:3.11-slim

WORKDIR /code

COPY requirements/streamlit.txt requirements/streamlit.txt
RUN pip install --no-cache-dir -r requirements/streamlit.txt

COPY app/streamlit_app.py app/streamlit_app.py

EXPOSE 8501
CMD ["streamlit", "run", "app/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
