FROM python:3.11-slim

WORKDIR /mlflow

COPY requirements/mlflow.txt requirements/mlflow.txt
RUN pip install --no-cache-dir -r requirements/mlflow.txt

EXPOSE 5000
CMD ["mlflow", "server", \
     "--host", "0.0.0.0", "--port", "5000", \
     "--backend-store-uri", "sqlite:////mlflow-data/mlflow.db", \
     "--artifacts-destination", "/mlflow-data/mlartifacts", \
     "--allowed-hosts", "mlflow:5000,localhost:5000,127.0.0.1:5000"]
