FROM apache/airflow:3.1.0-python3.11

COPY requirements/airflow.txt /requirements/airflow.txt
RUN pip install --no-cache-dir -r /requirements/airflow.txt

ENV PROJECT_DIR=/opt/airflow/project
ENV PYTHONPATH=/opt/airflow/project

CMD ["standalone"]